const app = document.getElementById('app');

const state = {
  view: 'home',
  role: null,
  farmerTab: 'dashboard',
  buyerTab: 'dashboard',
  adminTab: 'dashboard',
  lots: [
    {id:'LOT-KL-1024', crop:'Tomato', qty:1000, grade:'A', price:32, location:'Hyderabad', status:'Available', harvest:'02 Sep 2026'},
    {id:'LOT-KL-1021', crop:'Chilli', qty:700, grade:'A', price:118, location:'Warangal', status:'Offer received', harvest:'31 Aug 2026'}
  ],
  offers: [
    {id:'OF-3041', buyer:'ABC Foods Pvt Ltd', crop:'Tomato', qty:500, price:34, match:94, status:'Pending', payment:'3 days'},
    {id:'OF-3019', buyer:'FreshMart Retail', crop:'Tomato', qty:700, price:33, match:87, status:'Pending', payment:'2 days'}
  ],
  transactions: [
    {id:'TX-2018', crop:'Chilli', buyer:'Green Basket Foods', qty:300, total:35400, status:'Delivered', payment:'Payment received'},
    {id:'TX-2014', crop:'Tomato', buyer:'ABC Foods Pvt Ltd', qty:500, total:17000, status:'Confirmed', payment:'Pending'}
  ],
  requirements: [
    {id:'REQ-80', buyer:'ABC Foods Pvt Ltd', crop:'Tomato', qty:5000, grade:'A', max:35, location:'Hyderabad', terms:'3 days', verified:true},
    {id:'REQ-77', buyer:'FreshMart Retail', crop:'Tomato', qty:2000, grade:'A/B', max:34, location:'Secunderabad', terms:'2 days', verified:true},
    {id:'REQ-72', buyer:'Deccan Processors', crop:'Chilli', qty:3000, grade:'A', max:126, location:'Warangal', terms:'5 days', verified:true}
  ],
  toast: null
};

function money(n){return '₹'+Number(n).toLocaleString('en-IN');}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function toast(msg){state.toast=msg; render(); setTimeout(()=>{state.toast=null; render();},2300)}

function navBar(type='public'){
  const logged = type !== 'public';
  return `<div class="nav"><div class="container nav-inner">
    <a class="brand" href="#" onclick="go('home')"><span class="brand-mark">K</span><span>KrishiLink</span></a>
    <div class="nav-actions">
      ${logged ? `<button class="btn btn-outline optional" onclick="go('home')">Home</button><button class="btn btn-primary btn-sm" onclick="logout()">Log out</button>` : `<button class="btn btn-outline optional" onclick="go('login')">Log in</button><button class="btn btn-primary" onclick="go('register')">Register</button>`}
    </div>
  </div></div>`;
}

function pageShell(role, active, body){
  const menus = role==='farmer' ? [
    ['dashboard','⌂','Dashboard'],['market','📈','Market Intelligence'],['lot','🌾','Create Crop Lot'],['lots','▦','My Lots'],['offers','🤝','Offers'],['transactions','✓','Transactions']
  ] : role==='buyer' ? [
    ['dashboard','⌂','Dashboard'],['requirements','📋','Requirements'],['createReq','＋','Post Requirement'],['farmerLots','🌾','Farmer Lots'],['offers','🤝','Offers'],['transactions','✓','Transactions']
  ] : [['dashboard','⌂','Dashboard'],['users','👥','Users'],['verify','✓','Verify Buyers'],['transactions','↔','Transactions'],['complaints','⚑','Complaints']];
  return `${navBar(role)}<div class="shell"><aside class="sidebar"><div class="side-title">${role==='farmer'?'Farmer workspace':role==='buyer'?'Buyer workspace':'Admin workspace'}</div><div class="side-nav">${menus.map(m=>`<button class="side-btn ${active===m[0]?'active':''}" onclick="tab('${role}','${m[0]}')"><span>${m[1]}</span>${m[2]}</button>`).join('')}</div><div class="card" style="margin:24px 6px 0;padding:15px;box-shadow:none"><div style="font-size:12px;color:var(--muted);font-weight:700">Prototype mode</div><div style="font-size:13px;margin-top:5px;line-height:1.45">Demo data is stored in this browser. Connect Supabase/API later for live data.</div></div></aside><main class="main">${body}</main></div>${state.toast?`<div style="position:fixed;right:24px;bottom:24px;background:#173f30;color:#fff;padding:13px 15px;border-radius:12px;box-shadow:var(--shadow);z-index:50;font-size:13px;font-weight:800">${esc(state.toast)}</div>`:''}`;
}

function home(){
  return `${navBar()}<main class="container">
    <section class="hero">
      <span class="eyebrow">🌾 Farm-to-market intelligence</span>
      <h1>Know the market. Choose the buyer. Get the right price.</h1>
      <p>KrishiLink helps farmers and FPOs compare nearby prices, understand the best selling window, connect with verified buyers, and complete transparent transactions.</p>
      <div class="hero-cta"><button class="btn btn-primary" onclick="go('login');state.role='farmer'">Open Farmer Demo</button><button class="btn btn-outline" onclick="go('login');state.role='buyer'">Open Buyer Demo</button></div>
      <div class="stat-strip">
        <div class="stat"><div class="kpi">94%</div><div class="label">Best buyer match</div></div><div class="stat"><div class="kpi">₹34/kg</div><div class="label">Top tomato offer</div></div><div class="stat"><div class="kpi">3 days</div><div class="label">Typical payment window</div></div><div class="stat"><div class="kpi">1 place</div><div class="label">From price discovery to payment</div></div>
      </div>
    </section>
    <section class="feature-grid">
      <div class="card"><div class="icon-box">📈</div><h3>Localized price intelligence</h3><p>Compare nearby markets, trend direction, arrival volumes, and estimated net realization before deciding when and where to sell.</p></div>
      <div class="card"><div class="icon-box">🎯</div><h3>Smart buyer matching</h3><p>Rank verified buyers using price, quantity, quality, distance, and payment reliability—not just the highest headline price.</p></div>
      <div class="card"><div class="icon-box">🔒</div><h3>Transparent transactions</h3><p>Create crop lots, exchange digital offers, coordinate logistics, and keep a clear record of delivery, payment, and grievances.</p></div>
    </section>
    <section class="card center" style="margin-bottom:28px"><div class="eyebrow" style="margin-bottom:15px">SIH prototype flow</div><h2 style="color:var(--soil);margin:0 0 8px">Farmer → Intelligence → Buyer → Transaction</h2><p style="max-width:720px;margin:0 auto;color:var(--muted)">The demo is designed around one complete journey so judges can see how KrishiLink improves price discovery and turns it into an actual sale.</p></section>
  </main><footer class="footer">KrishiLink · SIH demonstration prototype · Demo data only</footer>`;
}

function login(){
  const role=state.role||'farmer';
  return `${navBar()}<div class="auth-wrap"><div class="card auth-card"><h1>Welcome to KrishiLink</h1><p class="sub">Choose a demo role and enter the dashboard.</p><div class="role-tabs">${[['farmer','🌾 Farmer'],['buyer','🏪 Buyer'],['admin','🛡 Admin']].map(x=>`<button class="role-tab ${role===x[0]?'active':''}" onclick="state.role='${x[0]}';render()">${x[1]}</button>`).join('')}</div><form class="form" onsubmit="event.preventDefault();loginGo()"><div class="field"><label>Mobile or email</label><input value="${role==='farmer'?'farmer@krishilink.demo':role==='buyer'?'buyer@krishilink.demo':'admin@krishilink.demo'}" required></div><div class="field"><label>Password</label><input type="password" value="demo123" required></div><button class="btn btn-primary" type="submit">Continue to ${esc(role)} dashboard →</button><div class="helper">Prototype login: any non-empty values will work.</div></form></div></div>`;
}
function register(){
  return `${navBar()}<div class="auth-wrap"><div class="card auth-card"><h1>Create your KrishiLink account</h1><p class="sub">This prototype uses browser-only demo data. Choose the role you want to explore.</p><form class="form" onsubmit="event.preventDefault();state.role=document.getElementById('regRole').value;toast('Demo account created');setTimeout(loginGo,350)"><div class="field"><label>Full name</label><input placeholder="e.g. Ramesh Kumar" required></div><div class="field"><label>Phone</label><input placeholder="10-digit mobile" required></div><div class="field"><label>Role</label><select id="regRole"><option value="farmer">Farmer / FPO</option><option value="buyer">Buyer</option></select></div><div class="field"><label>Location</label><input placeholder="Hyderabad, Telangana" required></div><button class="btn btn-primary">Create demo account</button></form></div></div>`;
}
function loginGo(){go(state.role==='buyer'?'buyer':state.role==='admin'?'admin':'farmer')}
function logout(){state.role=null;go('home')}

function farmerBody(){
  const tab=state.farmerTab;
  if(tab==='market') return farmerMarket();
  if(tab==='lot') return farmerCreateLot();
  if(tab==='lots') return farmerLots();
  if(tab==='offers') return farmerOffers();
  if(tab==='transactions') return farmerTransactions();
  return farmerDashboard();
}
function farmerDashboard(){
  return `<div class="page-head"><div><h1>Good evening, Ramesh 👋</h1><p>Here is today's selling intelligence for your farm.</p></div><button class="btn btn-primary" onclick="tab('farmer','lot')">＋ Create crop lot</button></div>
    <div class="grid-4"><div class="card kpi-card"><div class="kpi-label">Best tomato price</div><div class="kpi-value">₹34/kg</div><div class="trend">↑ 6.2% this week</div></div><div class="card kpi-card"><div class="kpi-label">Active crop lots</div><div class="kpi-value">${state.lots.filter(x=>x.status!=='Sold').length}</div><div class="trend">2 lots listed</div></div><div class="card kpi-card"><div class="kpi-label">Best buyer match</div><div class="kpi-value">94%</div><div class="trend">ABC Foods</div></div><div class="card kpi-card"><div class="kpi-label">Pending payment</div><div class="kpi-value">₹17,000</div><div class="trend" style="color:var(--gold)">Due in 2 days</div></div></div>
    <div class="grid-2 mt"><div class="card reco"><div class="small">AI-assisted sale-window recommendation · demo</div><h3>Recommended selling window</h3><div class="reco-price">Next 2–3 days</div><div class="small">Expected tomato range</div><div style="font-size:16px;font-weight:900;margin-top:3px">₹32–₹34/kg</div><div class="reco-row"><span>Reason</span><span>Nearby arrivals falling + buyer demand high</span></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:14px"><span class="pill">Potential upside +₹2/kg</span><span style="font-size:12px">Prototype model</span></div></div><div class="card"><div class="section-title" style="margin-top:0"><h2>Tomato price trend</h2><span>Hyderabad region</span></div><div class="chart"><svg viewBox="0 0 600 210" preserveAspectRatio="none"><line class="axis" x1="35" y1="30" x2="35" y2="180"/><line class="axis" x1="35" y1="180" x2="580" y2="180"/><line class="axis" x1="35" y1="130" x2="580" y2="130"/><line class="axis" x1="35" y1="80" x2="580" y2="80"/><polyline class="line" points="45,145 150,135 255,112 360,120 465,90 565,64"/><circle class="dot" cx="45" cy="145" r="5"/><circle class="dot" cx="150" cy="135" r="5"/><circle class="dot" cx="255" cy="112" r="5"/><circle class="dot" cx="360" cy="120" r="5"/><circle class="dot" cx="465" cy="90" r="5"/><circle class="dot" cx="565" cy="64" r="5"/><text x="38" y="201">Mon</text><text x="143" y="201">Tue</text><text x="248" y="201">Wed</text><text x="353" y="201">Thu</text><text x="458" y="201">Fri</text><text x="550" y="201">Sat</text><text x="8" y="185">₹24</text><text x="8" y="135">₹28</text><text x="8" y="85">₹32</text></svg></div></div></div>
    <div class="grid-2 mt"><div class="card"><div class="section-title" style="margin-top:0"><h2>Recommended buyers</h2><span>Ranked by net realisation</span></div>${buyerMatches()}</div><div class="card"><div class="section-title" style="margin-top:0"><h2>Latest offer activity</h2><span>Today</span></div>${state.offers.slice(0,3).map(o=>`<div style="padding:12px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(o.buyer)}</b><span class="badge green">${o.match}% match</span></div><div style="font-size:12px;color:var(--muted);margin-top:3px">${o.qty} kg ${o.crop} · <b style="color:var(--soil)">${money(o.price)}/kg</b> · ${o.payment}</div></div>`).join('')}</div></div>`;
}
function buyerMatches(){
  return [
    {name:'ABC Foods Pvt Ltd',score:94,price:34,reason:'Price + quantity + reliability',loc:'38 km',rel:'95%'},
    {name:'FreshMart Retail',score:87,price:33,reason:'Strong quality fit',loc:'22 km',rel:'91%'},
    {name:'Green Basket Foods',score:81,price:32.5,reason:'Closest logistics route',loc:'15 km',rel:'86%'}
  ].map(x=>`<div class="match" style="padding:12px 0;border-bottom:1px solid var(--line)"><div class="avatar">${x.name[0]}</div><div class="match-main"><div class="match-top"><span>${esc(x.name)}</span><span style="color:var(--brand)">${x.score}%</span></div><div class="match-sub">${money(x.price)}/kg · ${x.loc} · reliability ${x.rel}</div><div class="progress"><div style="width:${x.score}%"></div></div><div class="match-sub" style="margin-top:6px">${esc(x.reason)}</div></div><button class="btn btn-soft btn-sm" onclick="makeOffer('${x.name}',${x.price})">View</button></div>`).join('');
}
function farmerMarket(){
  const rows=[['Hyderabad Mandi',28,620,'22 km'],['Warangal Mandi',31,420,'145 km'],['Nalgonda Mandi',29,310,'95 km'],['ABC Foods',34,5000,'38 km'],['FreshMart',33,2000,'22 km']];
  return `<div class="page-head"><div><h1>Market Intelligence</h1><p>Compare market prices and buyer demand before you sell.</p></div><select class="btn btn-outline" style="padding:10px 12px"><option>Tomato</option><option>Chilli</option><option>Onion</option></select></div><div class="grid-3"><div class="card kpi-card"><div class="kpi-label">Highest price</div><div class="kpi-value">₹34/kg</div><div class="trend">ABC Foods</div></div><div class="card kpi-card"><div class="kpi-label">Market average</div><div class="kpi-value">₹30.4/kg</div><div class="trend">Across 5 channels</div></div><div class="card kpi-card"><div class="kpi-label">Net realisation</div><div class="kpi-value">₹32.4/kg</div><div class="trend">After estimated logistics</div></div></div><div class="grid-2 mt"><div class="card"><div class="section-title" style="margin-top:0"><h2>Price trend</h2><span>Last 6 days</span></div><div class="chart"><svg viewBox="0 0 600 210" preserveAspectRatio="none"><line class="axis" x1="35" y1="30" x2="35" y2="180"/><line class="axis" x1="35" y1="180" x2="580" y2="180"/><polyline class="line" points="45,148 150,140 255,122 360,130 465,94 565,62"/><circle class="dot" cx="45" cy="148" r="5"/><circle class="dot" cx="150" cy="140" r="5"/><circle class="dot" cx="255" cy="122" r="5"/><circle class="dot" cx="360" cy="130" r="5"/><circle class="dot" cx="465" cy="94" r="5"/><circle class="dot" cx="565" cy="62" r="5"/></svg></div><div class="notice">💡 <b>Recommendation:</b> buyer demand is stronger than mandi arrivals in this demo dataset. Compare net realisation before choosing Warangal's higher displayed mandi price.</div></div><div class="card"><div class="section-title" style="margin-top:0"><h2>What affects your price?</h2></div><div style="display:grid;gap:12px"><div><b style="font-size:13px">Arrivals</b><div class="progress"><div style="width:58%"></div></div><div class="helper">Lower arrivals can support prices.</div></div><div><b style="font-size:13px">Buyer demand</b><div class="progress"><div style="width:84%"></div></div><div class="helper">Institutional demand is high this week.</div></div><div><b style="font-size:13px">Storage availability</b><div class="progress"><div style="width:42%"></div></div><div class="helper">Only short-term storage appears available in this demo.</div></div></div></div></div><div class="card mt"><div class="section-title" style="margin-top:0"><h2>Nearby price and buyer comparison</h2><span>Demo data</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Channel</th><th>Price</th><th>Arrivals / demand</th><th>Distance</th><th>Type</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td><b style="color:var(--soil)">₹${r[1]}/kg</b></td><td>${r[2].toLocaleString('en-IN')}</td><td>${r[3]}</td><td><span class="badge ${i<3?'gray':'green'}">${i<3?'Mandi':'Buyer'}</span></td></tr>`).join('')}</tbody></table></div></div>`;
}
function farmerCreateLot(){
  return `<div class="page-head"><div><h1>Create Crop Lot</h1><p>Turn your harvest into a buyer-ready lot with quality and pricing details.</p></div></div><div class="card"><form class="form" style="max-width:820px" onsubmit="createLot(event)"><div class="grid-2"><div class="field"><label>Crop</label><select id="lotCrop"><option>Tomato</option><option>Chilli</option><option>Onion</option><option>Potato</option></select></div><div class="field"><label>Variety</label><input id="lotVariety" placeholder="e.g. Hybrid Tomato" required></div></div><div class="grid-2"><div class="field"><label>Quantity (kg)</label><input id="lotQty" type="number" min="1" placeholder="1000" required></div><div class="field"><label>Quality grade</label><select id="lotGrade"><option>A</option><option>B</option><option>Mixed</option></select></div></div><div class="grid-2"><div class="field"><label>Harvest date</label><input id="lotHarvest" type="date" required></div><div class="field"><label>Expected price (₹/kg)</label><input id="lotPrice" type="number" min="1" placeholder="32" required></div></div><div class="grid-2"><div class="field"><label>Moisture / quality note</label><input id="lotMoisture" placeholder="Fresh, dry surface, uniform size"></div><div class="field"><label>Location</label><input id="lotLocation" placeholder="Hyderabad, Telangana" required></div></div><div class="field"><label>Description</label><textarea id="lotDesc" placeholder="Add any buyer-relevant notes..."></textarea></div><div style="display:flex;gap:10px;align-items:center"><button class="btn btn-primary">Create lot</button><button type="button" class="btn btn-outline" onclick="tab('farmer','dashboard')">Cancel</button></div><div class="helper">Demo: photos, digital grading, and real buyer notifications can be connected next.</div></form></div>`;
}
function createLot(e){e.preventDefault();const crop=document.getElementById('lotCrop').value,qty=+document.getElementById('lotQty').value,grade=document.getElementById('lotGrade').value,price=+document.getElementById('lotPrice').value,loc=document.getElementById('lotLocation').value;const id='LOT-KL-'+(1030+state.lots.length);state.lots.unshift({id,crop,qty,grade,price,location:loc,status:'Available',harvest:'05 Sep 2026'});toast('Crop lot created successfully');setTimeout(()=>tab('farmer','lots'),350)}
function farmerLots(){return `<div class="page-head"><div><h1>My Crop Lots</h1><p>Track listed harvests and buyer activity.</p></div><button class="btn btn-primary" onclick="tab('farmer','lot')">＋ Create another lot</button></div><div class="lot-grid">${state.lots.map(l=>`<div class="card lot"><div class="top"><div><h3>${esc(l.crop)}</h3><div class="crop">${l.id}</div></div><span class="badge ${l.status==='Available'?'green':'gold'}">${esc(l.status)}</span></div><div class="lot-price">₹${l.price}/kg</div><div class="crop">Expected price</div><div class="lot-meta"><div class="meta"><span>Quantity</span><b>${l.qty.toLocaleString('en-IN')} kg</b></div><div class="meta"><span>Quality</span><b>Grade ${l.grade}</b></div><div class="meta"><span>Location</span><b>${esc(l.location)}</b></div><div class="meta"><span>Harvest</span><b>${esc(l.harvest)}</b></div></div><div style="display:flex;gap:8px;margin-top:14px"><button class="btn btn-soft btn-sm" onclick="tab('farmer','offers')">View offers</button><button class="btn btn-outline btn-sm" onclick="toast('Lot details opened')">Details</button></div></div>`).join('')}</div>`}
function farmerOffers(){return `<div class="page-head"><div><h1>Offers</h1><p>Compare verified buyer offers and negotiate digitally.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Buyer</th><th>Crop</th><th>Qty</th><th>Offer</th><th>Match</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>${state.offers.map(o=>`<tr><td><b>${esc(o.buyer)}</b><div class="helper">✓ Verified buyer</div></td><td>${o.crop}</td><td>${o.qty} kg</td><td><b style="color:var(--soil)">₹${o.price}/kg</b></td><td><span class="badge green">${o.match}%</span></td><td>${o.payment}</td><td><span class="badge gold">${o.status}</span></td><td><button class="btn btn-primary btn-sm" onclick="acceptOffer('${o.id}')">Accept</button> <button class="btn btn-outline btn-sm" onclick="toast('Counter-offer screen opened')">Counter</button></td></tr>`).join('')}</tbody></table></div></div>`}
function acceptOffer(id){const o=state.offers.find(x=>x.id===id);if(!o)return;o.status='Accepted';state.transactions.unshift({id:'TX-'+(2025+state.transactions.length),crop:o.crop,buyer:o.buyer,qty:o.qty,total:o.qty*o.price,status:'Confirmed',payment:'Pending'});toast('Offer accepted — transaction created');render()}
function makeOffer(b,p){toast(`Buyer profile: ${b} · current demo offer ₹${p}/kg`)}
function farmerTransactions(){return `<div class="page-head"><div><h1>Transactions</h1><p>Every step from acceptance to payment is recorded.</p></div></div><div class="grid-2">${state.transactions.map(t=>`<div class="card"><div style="display:flex;justify-content:space-between;gap:10px"><div><h3 style="margin:0">${esc(t.id)}</h3><div class="helper">${esc(t.crop)} · ${t.qty} kg · ${esc(t.buyer)}</div></div><span class="badge ${t.status==='Delivered'?'green':'gold'}">${esc(t.status)}</span></div><div style="margin:18px 0"><div class="timeline"><div class="step done"><div class="step-dot">✓</div><div><b>Offer accepted</b><span>Deal confirmed at agreed price.</span></div></div><div class="step done"><div class="step-dot">✓</div><div><b>Pickup scheduled</b><span>Transport coordination recorded.</span></div></div><div class="step ${t.status==='Delivered'?'done':'active'}"><div class="step-dot">${t.status==='Delivered'?'✓':'3'}</div><div><b>Delivery</b><span>${t.status==='Delivered'?'Buyer confirmed receipt.':'Awaiting delivery.'}</span></div></div><div class="step ${t.payment==='Payment received'?'done':'active'}"><div class="step-dot">${t.payment==='Payment received'?'✓':'4'}</div><div><b>Payment</b><span>${t.payment}</span></div></div></div></div><div style="display:flex;justify-content:space-between;align-items:center;padding-top:12px;border-top:1px solid var(--line)"><span class="helper">Transaction value</span><b style="font-size:20px;color:var(--soil)">${money(t.total)}</b></div></div>`).join('')}</div>`}

function buyerBody(){const t=state.buyerTab;if(t==='requirements')return buyerRequirements();if(t==='createReq')return buyerCreateReq();if(t==='farmerLots')return buyerFarmerLots();if(t==='offers')return buyerOffers();if(t==='transactions')return buyerTransactions();return buyerDashboard()}
function buyerDashboard(){return `<div class="page-head"><div><h1>Buyer dashboard</h1><p>Source consistent quality and volume from verified farmers and FPOs.</p></div><button class="btn btn-primary" onclick="tab('buyer','createReq')">＋ Post requirement</button></div><div class="grid-4"><div class="card kpi-card"><div class="kpi-label">Active requirements</div><div class="kpi-value">${state.requirements.length}</div><div class="trend">2 need action today</div></div><div class="card kpi-card"><div class="kpi-label">Available farmer lots</div><div class="kpi-value">18</div><div class="trend">Across 4 crops</div></div><div class="card kpi-card"><div class="kpi-label">Average match</div><div class="kpi-value">91%</div><div class="trend">Quality + quantity fit</div></div><div class="card kpi-card"><div class="kpi-label">This month</div><div class="kpi-value">₹8.4L</div><div class="trend">Order value</div></div></div><div class="grid-2 mt"><div class="card"><div class="section-title" style="margin-top:0"><h2>Open requirements</h2><span>Priority sourcing</span></div>${state.requirements.map(r=>`<div style="padding:13px 0;border-bottom:1px solid var(--line)"><div style="display:flex;justify-content:space-between"><b>${r.crop} · ${r.qty.toLocaleString('en-IN')} kg</b><span class="badge green">✓ Verified</span></div><div class="helper" style="margin-top:4px">Grade ${r.grade} · max ₹${r.max}/kg · ${r.location}</div></div>`).join('')}</div><div class="card"><div class="section-title" style="margin-top:0"><h2>Best farmer lots</h2><span>Matched to demand</span></div>${['LOT-KL-1024 · Tomato · 1000 kg · Grade A','LOT-KL-1012 · Chilli · 700 kg · Grade A','LOT-KL-0997 · Onion · 1500 kg · Grade A/B'].map((x,i)=>`<div style="padding:13px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px"><div><b>${x}</b><div class="helper">${i+1===1?'₹118/kg':'₹'+(34-i)+'/kg'} · ${['Hyderabad','Warangal','Nizamabad'][i]}</div></div><span class="badge ${i===0?'green':'gray'}">${94-i*7}% match</span></div>`).join('')}</div></div>`}
function buyerRequirements(){return `<div class="page-head"><div><h1>Requirements</h1><p>Manage what your business needs from farmers and FPOs.</p></div><button class="btn btn-primary" onclick="tab('buyer','createReq')">＋ New requirement</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Requirement</th><th>Quantity</th><th>Max price</th><th>Quality</th><th>Location</th><th>Payment</th><th>Status</th></tr></thead><tbody>${state.requirements.map(r=>`<tr><td><b>${r.crop}</b><div class="helper">${r.id}</div></td><td>${r.qty.toLocaleString('en-IN')} kg</td><td>₹${r.max}/kg</td><td>Grade ${r.grade}</td><td>${r.location}</td><td>${r.terms}</td><td><span class="badge green">Active</span></td></tr>`).join('')}</tbody></table></div></div>`}
function buyerCreateReq(){return `<div class="page-head"><div><h1>Post buyer requirement</h1><p>Tell farmers exactly what volume and quality you need.</p></div></div><div class="card"><form class="form" style="max-width:820px" onsubmit="event.preventDefault();const crop=document.getElementById('reqCrop').value,qty=+document.getElementById('reqQty').value,max=+document.getElementById('reqMax').value,loc=document.getElementById('reqLoc').value;state.requirements.unshift({id:'REQ-'+(80+state.requirements.length),buyer:'Demo Buyer',crop,qty,grade:document.getElementById('reqGrade').value,max,location:loc,terms:document.getElementById('reqTerms').value,verified:true});toast('Requirement published');setTimeout(()=>tab('buyer','requirements'),350)"><div class="grid-2"><div class="field"><label>Crop</label><select id="reqCrop"><option>Tomato</option><option>Chilli</option><option>Onion</option><option>Potato</option></select></div><div class="field"><label>Quantity needed (kg)</label><input id="reqQty" type="number" min="1" placeholder="5000" required></div></div><div class="grid-2"><div class="field"><label>Required quality</label><select id="reqGrade"><option>A</option><option>A/B</option><option>B</option></select></div><div class="field"><label>Maximum price (₹/kg)</label><input id="reqMax" type="number" min="1" placeholder="35" required></div></div><div class="grid-2"><div class="field"><label>Delivery location</label><input id="reqLoc" placeholder="Hyderabad" required></div><div class="field"><label>Payment terms</label><select id="reqTerms"><option>3 days</option><option>2 days</option><option>5 days</option><option>7 days</option></select></div></div><button class="btn btn-primary">Publish requirement</button></form></div>`}
function buyerFarmerLots(){const lots=[{id:'LOT-KL-1024',crop:'Tomato',qty:1000,grade:'A',price:32,loc:'Hyderabad',score:94},{id:'LOT-KL-1012',crop:'Chilli',qty:700,grade:'A',price:118,loc:'Warangal',score:91},{id:'LOT-KL-0997',crop:'Onion',qty:1500,grade:'A/B',price:29,loc:'Nizamabad',score:86}];return `<div class="page-head"><div><h1>Farmer lots</h1><p>Find crop lots that fit your requirements.</p></div></div><div class="lot-grid">${lots.map(l=>`<div class="card lot"><div class="top"><div><h3>${l.crop}</h3><div class="crop">${l.id} · ${l.loc}</div></div><span class="badge green">${l.score}% match</span></div><div class="lot-price">₹${l.price}/kg</div><div class="crop">Farmer asking price</div><div class="lot-meta"><div class="meta"><span>Quantity</span><b>${l.qty.toLocaleString('en-IN')} kg</b></div><div class="meta"><span>Quality</span><b>Grade ${l.grade}</b></div></div><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="toast('Offer form opened for ${l.id}')">Make offer</button></div>`).join('')}</div>`}
function buyerOffers(){return `<div class="page-head"><div><h1>Offers</h1><p>Track outbound and received digital offers.</p></div></div><div class="card"><div class="empty">No buyer-side offers have been sent in this demo yet.<br><button class="btn btn-soft" style="margin-top:12px" onclick="tab('buyer','farmerLots')">Browse farmer lots</button></div></div>`}
function buyerTransactions(){return `<div class="page-head"><div><h1>Transactions</h1><p>Purchase orders and supplier payment status.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Transaction</th><th>Supplier</th><th>Crop</th><th>Value</th><th>Status</th><th>Payment</th></tr></thead><tbody>${[{id:'PO-2081',supplier:'Ramesh FPO',crop:'Tomato',value:17000,status:'Confirmed',pay:'Pending'},{id:'PO-2075',supplier:'Warangal Producer Group',crop:'Chilli',value:82600,status:'Delivered',pay:'Paid'}].map(x=>`<tr><td><b>${x.id}</b></td><td>${x.supplier}</td><td>${x.crop}</td><td>${money(x.value)}</td><td><span class="badge ${x.status==='Delivered'?'green':'gold'}">${x.status}</span></td><td>${x.pay}</td></tr>`).join('')}</tbody></table></div></div>`}

function adminBody(){const t=state.adminTab;if(t==='users')return adminUsers();if(t==='verify')return adminVerify();if(t==='transactions')return adminTx();if(t==='complaints')return adminComplaints();return adminDashboard()}
function adminDashboard(){return `<div class="page-head"><div><h1>Admin dashboard</h1><p>Monitor trust, users, and transaction health.</p></div></div><div class="grid-4"><div class="card kpi-card"><div class="kpi-label">Farmers / FPOs</div><div class="kpi-value">1,250</div><div class="trend">+84 this month</div></div><div class="card kpi-card"><div class="kpi-label">Verified buyers</div><div class="kpi-value">185</div><div class="trend">92% verified</div></div><div class="card kpi-card"><div class="kpi-label">Active lots</div><div class="kpi-value">420</div><div class="trend">Across 12 districts</div></div><div class="card kpi-card"><div class="kpi-label">Open complaints</div><div class="kpi-value">12</div><div class="trend" style="color:var(--gold)">4 high priority</div></div></div><div class="grid-2 mt"><div class="card"><div class="section-title" style="margin-top:0"><h2>Trust & verification</h2></div><div style="display:grid;gap:12px"><div style="display:flex;justify-content:space-between"><span>Buyer KYC verification</span><b>92%</b></div><div class="progress"><div style="width:92%"></div></div><div style="display:flex;justify-content:space-between"><span>Transaction records complete</span><b>98%</b></div><div class="progress"><div style="width:98%"></div></div><div style="display:flex;justify-content:space-between"><span>Payment on-time rate</span><b>95%</b></div><div class="progress"><div style="width:95%"></div></div></div></div><div class="card"><div class="section-title" style="margin-top:0"><h2>Recent activity</h2><span>Today</span></div><div style="display:grid;gap:12px;font-size:13px"><div>✓ ABC Foods verified as buyer <span class="helper">10:24</span></div><div>✓ LOT-KL-1024 accepted offer <span class="helper">11:18</span></div><div>⚑ Payment complaint opened <span class="helper">12:05</span></div><div>✓ Green Basket completed delivery <span class="helper">13:42</span></div></div></div></div>`}
function adminUsers(){return `<div class="page-head"><div><h1>Users</h1><p>Sample trust directory for the prototype.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Role</th><th>Location</th><th>Status</th></tr></thead><tbody>${[['Ramesh Kumar','Farmer','Hyderabad','Active'],['ABC Foods Pvt Ltd','Buyer','Hyderabad','Verified'],['FreshMart Retail','Buyer','Secunderabad','Verified'],['Warangal FPO','FPO','Warangal','Active']].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td><span class="badge ${x[3]==='Verified'?'green':'gray'}">${x[3]}</span></td></tr>`).join('')}</tbody></table></div></div>`}
function adminVerify(){return `<div class="page-head"><div><h1>Verify buyers</h1><p>Keep buyer credentials and payment behaviour visible to farmers.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Buyer</th><th>Documents</th><th>Payment reliability</th><th>Action</th></tr></thead><tbody>${[['ABC Foods Pvt Ltd','Complete','95%'],['FreshMart Retail','Complete','91%'],['Deccan Processors','Under review','86%']].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[1]==='Complete'?'<span class="badge green">Verified</span>':'<button class="btn btn-primary btn-sm" onclick="toast(\'Buyer marked verified\')">Verify</button>'}</td></tr>`).join('')}</tbody></table></div></div>`}
function adminTx(){return `<div class="page-head"><div><h1>Transactions</h1><p>Platform-wide transaction monitoring.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Crop</th><th>Value</th><th>Status</th><th>Payment</th></tr></thead><tbody>${state.transactions.map(t=>`<tr><td><b>${t.id}</b></td><td>${t.crop}</td><td>${money(t.total)}</td><td><span class="badge ${t.status==='Delivered'?'green':'gold'}">${t.status}</span></td><td>${t.payment}</td></tr>`).join('')}</tbody></table></div></div>`}
function adminComplaints(){return `<div class="page-head"><div><h1>Complaints & grievances</h1><p>Resolve issues with auditable records.</p></div></div><div class="grid-2"><div class="card"><span class="badge red">High priority</span><h3 style="margin-top:12px">Payment delayed · TX-2014</h3><p>Farmer reports payment has not arrived after delivery confirmation.</p><div style="display:flex;gap:8px;margin-top:16px"><button class="btn btn-primary btn-sm" onclick="toast('Complaint assigned to support')">Assign support</button><button class="btn btn-outline btn-sm" onclick="toast('Complaint details opened')">View</button></div></div><div class="card"><span class="badge gold">Medium</span><h3 style="margin-top:12px">Quality dispute · TX-1998</h3><p>Buyer and FPO disagree about grade recorded at pickup.</p><div style="display:flex;gap:8px;margin-top:16px"><button class="btn btn-primary btn-sm" onclick="toast('Complaint assigned to quality team')">Assign</button><button class="btn btn-outline btn-sm" onclick="toast('Complaint details opened')">View</button></div></div></div>`}

function render(){
  if(state.view==='home') app.innerHTML=`<div class="app">${home()}</div>`;
  else if(state.view==='login') app.innerHTML=`<div class="app">${login()}</div>`;
  else if(state.view==='register') app.innerHTML=`<div class="app">${register()}</div>`;
  else if(state.view==='farmer') app.innerHTML=`<div class="app">${pageShell('farmer',state.farmerTab,farmerBody())}</div>`;
  else if(state.view==='buyer') app.innerHTML=`<div class="app">${pageShell('buyer',state.buyerTab,buyerBody())}</div>`;
  else if(state.view==='admin') app.innerHTML=`<div class="app">${pageShell('admin',state.adminTab,adminBody())}</div>`;
}
function go(v){state.view=v;render();window.scrollTo({top:0,behavior:'smooth'})}
function tab(role,t){if(role==='farmer')state.farmerTab=t;if(role==='buyer')state.buyerTab=t;if(role==='admin')state.adminTab=t;state.view=role;render();window.scrollTo({top:0,behavior:'smooth'})}
render();
